"object"!==typeof JSON2&&(JSON2=window.JSON||{});
(function(){function b(b){return 10>b?"0"+b:b}function y(b){G.lastIndex=0;return G.test(b)?'"'+b.replace(G,function(b){var e=z[b];return"string"===typeof e?e:"\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+b+'"'}function q(t,u){var e,l,m,v,c=n,p,g=u[t];g&&"object"===typeof g&&(e=g,m=Object.prototype.toString.apply(e),g="[object Date]"===m?isFinite(e.valueOf())?e.getUTCFullYear()+"-"+b(e.getUTCMonth()+1)+"-"+b(e.getUTCDate())+"T"+b(e.getUTCHours())+":"+b(e.getUTCMinutes())+":"+b(e.getUTCSeconds())+
"Z":null:"[object String]"===m||"[object Number]"===m||"[object Boolean]"===m?e.valueOf():"[object Array]"!==m&&"function"===typeof e.toJSON?e.toJSON(t):e);"function"===typeof r&&(g=r.call(u,t,g));switch(typeof g){case "string":return y(g);case "number":return isFinite(g)?String(g):"null";case "boolean":case "null":return String(g);case "object":if(!g)return"null";n+=B;p=[];if("[object Array]"===Object.prototype.toString.apply(g)){v=g.length;for(e=0;e<v;e+=1)p[e]=q(e,g)||"null";m=0===p.length?"[]":
n?"[\n"+n+p.join(",\n"+n)+"\n"+c+"]":"["+p.join(",")+"]";n=c;return m}if(r&&"object"===typeof r)for(v=r.length,e=0;e<v;e+=1)"string"===typeof r[e]&&(l=r[e],(m=q(l,g))&&p.push(y(l)+(n?": ":":")+m));else for(l in g)Object.prototype.hasOwnProperty.call(g,l)&&(m=q(l,g))&&p.push(y(l)+(n?": ":":")+m);m=0===p.length?"{}":n?"{\n"+n+p.join(",\n"+n)+"\n"+c+"}":"{"+p.join(",")+"}";n=c;return m}}var w=RegExp("[\x00­؀-؄܏឴឵‌-‏\u2028- ⁠-⁯﻿￰-￿]","g"),G=RegExp('[\\\\\\"\x00--­؀-؄܏឴឵‌-‏\u2028- ⁠-⁯﻿￰-￿]',"g"),n,
B,z={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},r;"function"!==typeof JSON2.stringify&&(JSON2.stringify=function(b,u,e){var l;B=n="";if("number"===typeof e)for(l=0;l<e;l+=1)B+=" ";else"string"===typeof e&&(B=e);if((r=u)&&"function"!==typeof u&&("object"!==typeof u||"number"!==typeof u.length))throw Error("JSON2.stringify");return q("",{"":b})});"function"!==typeof JSON2.parse&&(JSON2.parse=function(b,n){function e(b,l){var c,p,g=b[l];if(g&&"object"===typeof g)for(c in g)Object.prototype.hasOwnProperty.call(g,
c)&&(p=e(g,c),void 0!==p?g[c]=p:delete g[c]);return n.call(b,l,g)}var l;b=String(b);w.lastIndex=0;w.test(b)&&(b=b.replace(w,function(b){return"\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(b.replace(RegExp('\\\\(?:["\\\\/bfnrt]|u[0-9a-fA-F]{4})',"g"),"@").replace(RegExp('"[^"\\\\\n\r]*"|true|false|null|-?\\d+(?:\\.\\d*)?(?:[eE][+\\-]?\\d+)?',"g"),"]").replace(RegExp("(?:^|:|,)(?:\\s*\\[)+","g"),"")))return l=eval("("+b+")"),"function"===typeof n?e({"":l},""):l;throw new SyntaxError("JSON2.parse");
})})();"object"!==typeof _fd&&(_fd=[]);
(function(b,y,q){function w(){var a,f,b;for(a=0;a<arguments.length;a+=1)b=arguments[a],f=b.shift(),"string"===typeof f||f instanceof String?asyncTracker[f].apply(asyncTracker,b):f.apply(asyncTracker,b)}function G(a){var f=new Image,h="ab_log_"+Math.round(2147483647*Math.random()).toString(36);b[h]=f;f.onload=f.onerror=f.onabort=function(){f.onload=f.onerror=f.onabort=null;f=b[h]=null};f.src=a}function n(){var a,f,h;if((h=(h=b.navigator)?h.plugins:null)&&h.length)for(var C=0;C<h.length&&!f;C++){var c=
h[C];-1<c.name.indexOf("Shockwave Flash")&&(f=c.description)}if(!f)try{a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"),f=a.GetVariable("$version")}catch(e){}if(!f)try{a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),f="WIN 6,0,21,0",a.A="always",f=a.GetVariable("$version")}catch(k){}if(!f)try{a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),f=a.GetVariable("$version")}catch(g){}f&&(a=f.match(/[\d]+/g))&&2<=a.length&&(f=a[0]+"."+a[1]);return f||void 0}function B(){for(var a=b.navigator,
a=a.appName+a.version+a.platform+a.userAgent+(c.cookie?c.cookie:"")+(c.referrer?c.referrer:""),f=a.length,h=b.history.length;0<h;)a+=h--^f++;var f=1,h=0,C;if(a)for(f=0,C=a.length-1;0<=C;C--)h=a.charCodeAt(C),f=(f<<6&268435455)+h+(h<<14),h=f&266338304,0!=h&&(f=f^h>>21);return[Math.round(2147483647*Math.random())^f&2147483647,Math.round((new Date).getTime())].join("")}function z(a,b){if(a&&a.getAttribute)return a.getAttribute(b);if(!a||!a.attributes||"undefined"===typeof a.attributes[b])return q;if(a.attributes[b].value)return a.attributes[b].value;
if(a.attributes[b].nodeValue)return a.attributes[b].nodeValue;var h,c=a.attributes;if(!c)return q;for(h=0;h<c.length;h++)if(c[h].nodeName===b)return c[h].nodeValue;return q}function r(a){return a&&"object"===typeof a&&a.length&&"number"===typeof a.length}function t(a){return"undefined"!==typeof a}function u(a){for(var b in a)return!1;return!0}function e(a){return a&&"function"===typeof a?e(a()):"object"===typeof a||r(a)?JSON2.stringify(a):null!==a&&t(a)?String(a):""}function l(a,b){var c,e=0,k=a.length;
if(r(a))for(;e<k&&(c=b.call(a[e],e,a[e]),!1!==c);e++);else for(e in a)if(c=b.call(a[e],e,a[e]),!1===c)break}function m(a,b,c,e){a.attachEvent?a.attachEvent("on"+b,function(b){c.call(a,b)}):a.addEventListener&&a.addEventListener(b,c,!!e)}var v=b.performance||b.l||b.m||b.u,c=b.document,p=c.all&&b.XMLHttpRequest&&!c.querySelector,g=c.all&&c.querySelector&&!c.addEventListener,M=c.all&&c.addEventListener&&!b.atob,N=c.all&&c.compatMode&&!b.XMLHttpRequest||p||g||M,k={a:{CONFSTAR:!0,site_id:"fb",domain:"facebank.cn",
cookie_path:"/",session_timeout:1800,max_delay:300,host_alias:[],log_host:"collect.facebank.cn",log_path:{pv:"/col/pv",goal:"/col/goal",click:"/col/click",event:"/col/event"},performanceTracking:!0,debug:"CONFEND"}};k.a.host_alias.push(c.domain);k.waitUntil=0;k.c=function(){function a(){if(!k){k=!0;for(var a=0;a<g.length;a++)g[a]()}}function e(){c.addEventListener?(c.removeEventListener("DOMContentLoaded",h,!1),b.removeEventListener("load",h,!1)):(c.detachEvent("onreadystatechange",h),b.detachEvent("onload",
h))}function h(){if(c.addEventListener||"load"===event.type||"complete"===c.readyState)e(),a()}var k=!1,g=[];if("complete"===c.readyState)setTimeout(a);else if(c.addEventListener)c.addEventListener("DOMContentLoaded",h,!1),b.addEventListener("load",h,!1);else{c.attachEvent("onreadystatechange",h);b.attachEvent("onload",h);var l=!1;try{l=null==b.frameElement&&c.documentElement}catch(m){}l&&l.doScroll&&function O(){if(!k){try{l.doScroll("left")}catch(b){return setTimeout(O,50)}e();a()}}()}return function(a){k?
a():g.push(a)}}();m(b,"beforeunload",function(){var a;if(k.waitUntil){do a=new Date;while(a.getTime()<k.waitUntil)}},!1);asyncTracker=new function(){function a(d,a,b){var c={},e={},f;for(f in d)a.hasOwnProperty(f)?c[a[f]]=d[f]:e[f]=d[f];u(e)||(c[b]=e);return c}function f(d,a){for(var b=a||{},e=c.getElementsByTagName("Meta"),f=0;f<e.length;f+=1){var g=e[f],h=z(g,"name");h&&0==h.indexOf(d+"-")&&(b[h.substring(d.length+1)]=z(g,"content"))}return b}function h(d){var a,b,c,f,g=[];for(b in D)f=e(D[b]),
!f.length||d&&d.hasOwnProperty(b)||g.push(b+"="+encodeURIComponent(f));for(a=0;a<E.length;a+=1)for(b in c=E[a](),c)f=e(c[b]),!f.length||d&&d.hasOwnProperty(b)||g.push(b+"="+encodeURIComponent(f));if(d)for(b in d)f=e(d[b]),f.length&&g.push(b+"="+encodeURIComponent(f));g.push("_r="+String(Math.random()).slice(2,8));return g.join("&")}function g(d){return"_fd_"+d+"."+k.a.site_id}function p(d){if(1==x.f){d=d.target||d.srcElement;var a;if(a=null!=d.form&&t(d.form))a=d.tagName.toUpperCase(),a="INPUT"==
a||"SELECT"==a||"TEXTAREA";if(a){a=d.value||"";var b={len:a.length};"true"==z(d,"data-log-value")&&(b.value=a);H("/form/"+(d.form.id||d.form.name),d.name||d.id,"","",b)}}}function r(d){var a,b,c;for(a=0;a<k.a.host_alias.length;a++){b=k.a.host_alias[a].toLowerCase();if(d===b)return!0;if("."===b.slice(0,1)){if(d===b.slice(1))return!0;c=d.length-b.length;if(0<c&&d.slice(c)===b)return!0}}return!1}function q(d,a,f,e,g){var h;f&&(h=new Date,h.setTime(h.getTime()+f));"auto"==g&&(g=b.location.hostname);c.cookie=
d+"="+b.encodeURIComponent(a)+(f?";expires="+h.toGMTString():"")+";path="+(e||"/")+(g?";domain="+g:"")+""}function w(d){return(d=(new RegExp("(^|;)[ ]*"+d+"=([^;]*)")).exec(c.cookie))?b.decodeURIComponent(d[2]):0}function y(){var d;d=Math.round((new Date).getTime()/1E3);var a=w(g("id"));a?(d=a.split("."),d.unshift("0")):d=["1",B(),d,0,d,"",""];return{D:d[0],i:d[1],s:d[2],j:d[3],v:d[4],b:d[5],w:d[6]}}function I(d){var a=Math.round((new Date).getTime()/1E3);t(d)||(d=y());q(g("id"),d.i+"."+d.s+"."+d.j+
"."+a+"."+d.b+"."+d.w,339552E5,k.a.cookie_path,k.a.domain)}function J(d){return(d=/^([a-z]+):/.exec(d))?d[1]:null}function K(d){var a=/^(?:(?:https?|ftp):)\/*(?:[^@]+@)?([^:/#]+)/.exec(d);return a?a[1]:d}function L(d,a){var c=(new RegExp("[\\?&#]"+a+"=([^&#]*)")).exec(d);return c?b.decodeURIComponent(c[1]):""}function H(d,a,b,c,f){if(0!==String(d).length&&0!==String(a).length){d="http://"+k.a.log_host+k.a.log_path.event+"?"+h({_ecat:d,_eact:a,_en:b,_ev:c,ext:f});var e;e=e||k.a.max_delay;e=(new Date).getTime()+
e;e>k.waitUntil&&(k.waitUntil=e);G(d)}}var F=b.navigator,A=b.screen,D={ds:A&&A.width+"x"+A.height,cl:A&&A.colorDepth,vp:function(){var d=c.body,a=d&&d.clientWidth&&d.clientHeight,b=[];A&&A.clientWidth&&A.clientHeight&&("CSS1Compat"===c.compatMode||!a)?b=[A.clientWidth,A.clientHeight]:a&&(b=[d.clientWidth,d.clientHeight]);return 0>=b[0]||0>=b[1]?"":b.join("x")},dr:c.referrer,dt:c.title,fl:n(),st:b.sessionStorage?"1":"0",ck:F&&F.cookieEnabled?"1":"0",ln:F&&(F.language||F.browserLanguage||F.l||F.m||
"").toLowerCase(),sid:k.a.site_id||"0",pvid:B(),perf:function(){return!0===k.a.performanceTracking&&v&&v.timing&&v.timing.requestStart&&v.timing.responseEnd?v.timing.responseEnd-v.timing.requestStart:"0"}},E=[];E.push(function(){var d=Math.round((new Date).getTime()/1E3),a=y();if(!a.b||d-a.b>k.a.session_timeout)a.j++,a.b=a.v;I(a);return{guid:a.i,guidts:a.s,guidvc:a.j,guidlvts:a.b}});E.push(function(){var d;a:{var a=w(g("ref"));if(a.length&&(a=JSON2.parse(a),"object"===typeof a)){d=a;break a}d=["",
"",0,""]}var c=b.location.href,f,e,a=d[0];f=d[1];d=d[3];for(i in x.h)if(Object.prototype.hasOwnProperty.call(x.h,i)&&(e=L(c,x.h[i]),e.length)){a=e;break}for(i in x.g)if(Object.prototype.hasOwnProperty.call(x.g,i)&&(e=L(c,x.g[i]),e.length)){f=e;break}c=K(D.dr);c.length&&!r(c)&&(d=D.dr);return d.length||a.length?(c=Math.round((new Date).getTime()/1E3),d=[a,f,c,d.slice(0,1024)],q(g("ref"),JSON2.stringify(d),15768E6,k.a.cookie_path,k.a.domain),{_ref:d[3],_refcn:a,_refcv:f,_refts:c}):{}});E.push(function(){var a=
f("page");return t(a.name)?{pname:a.name}:{}});E.push(function(){var d;a:{d=w(g("u"));if(d.length&&(d=JSON2.parse(d),"object"===typeof d))break a;d={}}d=f("user",d);return a(d,{id:"uid"},"uvar")});E.push(function(){return a(f("content",x.o),{id:"cid",channel:"cch",subchannel:"cchs"},"cvar")});var x={h:"fd_campaign _from _ref utm_campaign utm_source utm_medium qq-pf-to".split(" "),g:["fd_kwd","utm_term"],o:{},B:{},f:!0};I();(function(){k.c(function(){m(b.document,"click",function(a){if(1==x.f){a:{a=
a.target||a.srcElement;for(var b=0;a&&a!==c&&a.parentNode;){if(z(a,"data-event")){a={category:z(a,"data-event-category")||"/",action:z(a,"data-event"),name:z(a,"data-event-name")||"",value:z(a,"data-event-value")||""};break a}a=a.parentNode;if(1E3<b)break;b++}a=void 0}a&&!u(a)&&H(a.category,a.action,a.name,a.value)}})})})();(function(){k.c(function(){N?l(["input","select","textarea"],function(){l(c.getElementsByTagName(this),function(){m(this,"change",p)})}):m(c,"change",p)})})();return{getGuid:function(){return y().i},
setUserInfo:function(a){!t(a)||u(a)?q(g("u"),"",-86400,k.a.cookie_path,k.a.domain):q(g("u"),JSON2.stringify(a),339552E5,k.a.cookie_path,k.a.domain)},setContentInfo:function(a){x.o=a||{}},l:function(a){D.dr=a},m:function(a){var c=b.location.href,e;J(a)||("/"===a.slice(0,1)?a=J(c)+"://"+K(c)+a:(e=c.indexOf("?"),0<=e&&(c=c.slice(0,e)),e=c.lastIndexOf("/"),e!==c.length-1&&(c=c.slice(0,e+1)),a=c+a));D.url=a},setDocumentTitle:function(a){D.dt=a},u:function(a,b,c){trackCallback(function(){logGoal(a,b,c)})},
C:function(a,b,c,e){trackCallback(function(){logLink(a,b,c,e)})},pageView:function(a,b){k.c(function(){var c={};t(a)&&(c.pname=a);t(b)&&(c.ext=b);c="http://"+k.a.log_host+k.a.log_path.pv+"?"+h(c);G(c)})},event:function(a,b,c,e){k.c(function(){H(a,b,c,e)})},autoEvent:function(){x.f=!0}}};_fd=function(a,b){var c,e;for(c=0;c<b.length;c++){var g=b[c];for(e=0;e<a.length;e++)a[e]&&a[e][0]&&g===a[e][0]&&(w(a[e]),delete a[e])}return a}(_fd,["setUserInfo","setContentInfo"]);for(iterator=0;iterator<_fd.length;iterator++)_fd[iterator]&&
w(_fd[iterator]);_fd=new function(){return{push:w}};b[y]=b[y]||k})(window,"FireData");
