
"object"!==typeof JSON2&&(JSON2=window.JSON||{});
(function(){function e(e){return 10>e?"0"+e:e}function y(e){G.lastIndex=0;return G.test(e)?'"'+e.replace(G,function(e){var f=k[e];return"string"===typeof f?f:"\\u"+("0000"+e.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+e+'"'}function z(v,C){var f,l,q,k,A=m,n,d=C[v];d&&"object"===typeof d&&(f=d,q=Object.prototype.toString.apply(f),d="[object Date]"===q?isFinite(f.valueOf())?f.getUTCFullYear()+"-"+e(f.getUTCMonth()+1)+"-"+e(f.getUTCDate())+"T"+e(f.getUTCHours())+":"+e(f.getUTCMinutes())+":"+e(f.getUTCSeconds())+
"Z":null:"[object String]"===q||"[object Number]"===q||"[object Boolean]"===q?f.valueOf():"[object Array]"!==q&&"function"===typeof f.toJSON?f.toJSON(v):f);"function"===typeof t&&(d=t.call(C,v,d));switch(typeof d){case "string":return y(d);case "number":return isFinite(d)?String(d):"null";case "boolean":case "null":return String(d);case "object":if(!d)return"null";m+=D;n=[];if("[object Array]"===Object.prototype.toString.apply(d)){k=d.length;for(f=0;f<k;f+=1)n[f]=z(f,d)||"null";q=0===n.length?"[]":
m?"[\n"+m+n.join(",\n"+m)+"\n"+A+"]":"["+n.join(",")+"]";m=A;return q}if(t&&"object"===typeof t)for(k=t.length,f=0;f<k;f+=1)"string"===typeof t[f]&&(l=t[f],(q=z(l,d))&&n.push(y(l)+(m?": ":":")+q));else for(l in d)Object.prototype.hasOwnProperty.call(d,l)&&(q=z(l,d))&&n.push(y(l)+(m?": ":":")+q);q=0===n.length?"{}":m?"{\n"+m+n.join(",\n"+m)+"\n"+A+"}":"{"+n.join(",")+"}";m=A;return q}}var w=RegExp("[\x00­؀-؄܏឴឵‌-‏\u2028- ⁠-⁯﻿￰-￿]","g"),G=RegExp('[\\\\\\"\x00--­؀-؄܏឴឵‌-‏\u2028- ⁠-⁯﻿￰-￿]',"g"),m,
D,k={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},t;"function"!==typeof JSON2.stringify&&(JSON2.stringify=function(e,k,f){var l;D=m="";if("number"===typeof f)for(l=0;l<f;l+=1)D+=" ";else"string"===typeof f&&(D=f);if((t=k)&&"function"!==typeof k&&("object"!==typeof k||"number"!==typeof k.length))throw Error("JSON2.stringify");return z("",{"":e})});"function"!==typeof JSON2.parse&&(JSON2.parse=function(e,k){function f(e,l){var m,n,d=e[l];if(d&&"object"===typeof d)for(m in d)Object.prototype.hasOwnProperty.call(d,
m)&&(n=f(d,m),void 0!==n?d[m]=n:delete d[m]);return k.call(e,l,d)}var l;e=String(e);w.lastIndex=0;w.test(e)&&(e=e.replace(w,function(e){return"\\u"+("0000"+e.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(e.replace(RegExp('\\\\(?:["\\\\/bfnrt]|u[0-9a-fA-F]{4})',"g"),"@").replace(RegExp('"[^"\\\\\n\r]*"|true|false|null|-?\\d+(?:\\.\\d*)?(?:[eE][+\\-]?\\d+)?',"g"),"]").replace(RegExp("(?:^|:|,)(?:\\s*\\[)+","g"),"")))return l=eval("("+e+")"),"function"===typeof k?f({"":l},""):l;throw new SyntaxError("JSON2.parse");
})})();"object"!==typeof _fd&&(_fd=[]);
(function(e,y,z){function w(){var a,b,c;for(a=0;a<arguments.length;a+=1)c=arguments[a],b=c.shift(),"string"===typeof b||b instanceof String?asyncTracker[b].apply(asyncTracker,c):b.apply(asyncTracker,c)}function G(a){var b=new Image,c="ab_log_"+Math.round(2147483647*Math.random()).toString(36);e[c]=b;b.onload=b.onerror=b.onabort=function(){b.onload=b.onerror=b.onabort=null;b=e[c]=null};b.src=a}function m(){var a,b,c;if((c=(c=e.navigator)?c.plugins:null)&&c.length)for(var d=0;d<c.length&&!b;d++){var f=
c[d];-1<f.name.indexOf("Shockwave Flash")&&(b=f.description)}if(!b)try{a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"),b=a.GetVariable("$version")}catch(h){}if(!b)try{a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),b="WIN 6,0,21,0",a.D="always",b=a.GetVariable("$version")}catch(h){}if(!b)try{a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),b=a.GetVariable("$version")}catch(h){}b&&(a=b.match(/[\d]+/g))&&2<=a.length&&(b=a[0]+"."+a[1]);return b||void 0}function D(){for(var a=e.navigator,
a=a.appName+a.version+a.platform+a.userAgent+(d.cookie?d.cookie:"")+(d.referrer?d.referrer:""),b=a.length,c=e.history.length;0<c;)a+=c--^b++;var b=1,c=0,p;if(a)for(b=0,p=a.length-1;0<=p;p--)c=a.charCodeAt(p),b=(b<<6&268435455)+c+(c<<14),c=b&266338304,0!=c&&(b^=c>>21);return[Math.round(2147483647*Math.random())^b&2147483647,Math.round((new Date).getTime())].join("")}function k(a,b){if(a&&a.getAttribute)return a.getAttribute(b);if(!a||!a.attributes||"undefined"===typeof a.attributes[b])return z;if(a.attributes[b].value)return a.attributes[b].value;
if(a.attributes[b].nodeValue)return a.attributes[b].nodeValue;var c,d=a.attributes;if(!d)return z;for(c=0;c<d.length;c++)if(d[c].nodeName===b)return d[c].nodeValue;return z}function t(a){return a&&"object"===typeof a&&a.length&&"number"===typeof a.length}function v(a){return null!==a&&"undefined"!==typeof a}function C(a){return"object"===typeof a}function f(a){for(var b in a)return!1;return!0}function l(){for(var a,b,c,d,e,f=arguments[0]||{},h=arguments.length,r=1;r<h;r++)if(null!=(e=arguments[r]))for(d in e)a=
f[d],c=e[d],f!==c&&(c&&(C(c)||(b=t(c)))?(b?(b=!1,a=a&&t(a)?a:[]):a=a&&C(a)?a:{},f[d]=l(a,c)):c!==z&&(f[d]=c));return f}function q(a){return a&&"function"===typeof a?q(a()):C(a)||t(a)?JSON2.stringify(a):v(a)?String(a):""}function N(a,b){var c,d=0,e=a.length;if(t(a))for(;d<e&&(c=b.call(a[d],d,a[d]),!1!==c);d++);else for(d in a)if(c=b.call(a[d],d,a[d]),!1===c)break}function A(a,d,c,e){a.attachEvent?a.attachEvent("on"+d,function(d){c.call(a,d)}):a.addEventListener&&a.addEventListener(d,c,!!e)}var n=e.performance||
e.M||e.N||e.W,d=e.document,V=d.all&&e.XMLHttpRequest&&!d.querySelector,W=d.all&&d.querySelector&&!d.addEventListener,X=d.all&&d.addEventListener&&!e.atob,O=d.all&&d.compatMode&&!e.XMLHttpRequest||V||W||X,h={a:{"autoEvent":true,"noWeblog":false,"autoevent2app":false,"cmpKws":["fd_kwd","utm_term"],"cmpParams":["fd_campaign","_from","_ref","utm_campaign","utm_source","utm_medium","qq-pf-to"],"domain":"facebank.cn","host_alias":["facebank.net.cn"],"log_host":"collect.facebank.cn","log_path":{"event":"/log/v2/9WAI779FPB/event"},"max_delay":300,"performanceTracking":true,"session_timeout":1800,"app_key":"9WAI779FPB","site_id":"9WAI779FPB"}};h.a.host_alias.push(d.domain);
h.waitUntil=0;h.b=function(){function a(){if(!f){f=!0;for(var a=0;a<h.length;a++)h[a]()}}function b(){d.addEventListener?(d.removeEventListener("DOMContentLoaded",c,!1),e.removeEventListener("load",c,!1)):(d.detachEvent("onreadystatechange",c),e.detachEvent("onload",c))}function c(){if(d.addEventListener||"load"===event.type||"complete"===d.readyState)b(),a()}var f=!1,h=[];if("complete"===d.readyState)setTimeout(a);else if(d.addEventListener)d.addEventListener("DOMContentLoaded",c,!1),e.addEventListener("load",
c,!1);else{d.attachEvent("onreadystatechange",c);e.attachEvent("onload",c);var l=!1;try{l=null==e.frameElement&&d.documentElement}catch(k){}l&&l.doScroll&&function r(){if(!f){try{l.doScroll("left")}catch(d){return setTimeout(r,50)}b();a()}}()}return function(a){f?a():h.push(a)}}();A(e,"beforeunload",function(){var a;if(h.waitUntil){do a=new Date;while(a.getTime()<h.waitUntil)}},!1);asyncTracker=new function(){function a(g,a,d){var c={},b={},e;for(e in g)a.hasOwnProperty(e)?c[a[e]]=g[e]:b[e]=g[e];
f(b)||(c[d]=b);return c}function b(g,a){for(var P=a||{},c=d.getElementsByTagName("Meta"),b=0;b<c.length;b+=1){var e=c[b],f=k(e,"name");f&&0==f.indexOf(g+"-")&&(P[f.substring(g.length+1)]=k(e,"content"))}return P}function c(g){return"_fd_"+g+"."+h.a.site_id}function p(g){g=g.tagName.toUpperCase();return"INPUT"===g||"SELECT"===g||"TEXTAREA"===g}function I(g){if(!1!==u.j&&(g=g.target||g.srcElement)){var a=t(g),d=a.category;!a.category&&v(g.form)&&(d="/form/"+(g.form.id||g.form.name));if(v(d)&&p(g)){var b=
g.value||"",c=a.action||g.name||g.id||"",a=l({len:b.length},a.evar);"password"!==k(g,"type")&&"@off"!==a.v&&(a.v=b);H(d,c,a)}}}function t(g){for(var a=0,b={};g&&g!==d&&g.parentNode;){if(!b.action&&k(g,"data-event")||p(g)){b.el=g;b.action=k(g,"data-event")||z;var c;if(g&&g.attributes){c=void 0;var e=g.attributes,f={};for(c=0;c<e.length;c++){var h=e[c],r=h.nodeName||h.name;0==r.indexOf("data-event-")&&(f[r.substring(11)]=h.nodeValue||h.value)}c=f}else c={};e=c;f={};for(name in e)"category"!==name&&
(f[name]=e[name]);b.evar=l(b.evar,f);if(c.category){b.category=c.category;break}}if(!b.category&&k(g,"data-event-category")){b.category=k(g,"data-event-category");break}g=g.parentNode;if(100<a)break;a++}return b}function U(g){var a,b,c;for(a=0;a<h.a.host_alias.length;a++){b=h.a.host_alias[a].toLowerCase();if(g===b)return!0;if("."===b.slice(0,1)){if(g===b.slice(1))return!0;c=g.length-b.length;if(0<c&&g.slice(c)===b)return!0}}return!1}function r(g,a,b,c,f){var h;b&&(h=new Date,h.setTime(h.getTime()+
b));"auto"==f&&(f=e.location.hostname);d.cookie=g+"\x3d"+e.encodeURIComponent(a)+(b?";expires\x3d"+h.toGMTString():"")+";path\x3d"+(c||"/")+(f?";domain\x3d"+f:"")+""}function w(g){return(g=(new RegExp("(^|;)[ ]*"+g+"\x3d([^;]*)")).exec(d.cookie))?e.decodeURIComponent(g[2]):0}function y(){var g;g=Math.round((new Date).getTime()/1E3);var a=w(c("id"));a?(g=a.split("."),g.unshift("0")):g=["1",D(),g,0,g,"",""];return{O:g[0],f:g[1],m:g[2],g:g[3],u:g[4],c:g[5],B:g[6]}}function Q(g){var a=Math.round((new Date).getTime()/
1E3);v(g)||(g=y());r(c("id"),g.f+"."+g.m+"."+g.g+"."+a+"."+g.c+"."+g.B,339552E5,h.a.cookie_path,h.a.domain)}function R(a){return(a=/^([a-z]+):/.exec(a))?a[1]:null}function S(a){var b=/^(?:(?:https?|ftp):)\/*(?:[^@]+@)?([^:/#]+)/.exec(a);return b?b[1]:a}function J(a,b){var c=(new RegExp("[\\?\x26#]"+b+"\x3d([^\x26#]*)")).exec(a);return c?e.decodeURIComponent(c[1]):""}function H(a,b,c){if(0!==String(a).length&&0!==String(b).length){"/"!=a.charAt(0)&&(a="/"+a);c=l({},c);var d,e={_ecat:a,_eact:b,evar:c},
f,p=[];c={};var r=u.w||{};for(d in r)f=q(r[d]),f.length&&p.push(d+"\x3d"+encodeURIComponent(f));for(d in E)f=q(E[d]),!f.length||e&&e.hasOwnProperty(d)||p.push(d+"\x3d"+encodeURIComponent(f));for(f=0;f<B.length;f+=1)l(c,B[f]());c.hasOwnProperty("evar")&&(e.evar=l(c.evar,e.evar||{}));e&&l(c,e);for(d in c)f=q(c[d]),f.length&&p.push(d+"\x3d"+encodeURIComponent(f));d=K.s(p.join("\x26"));d={evar:c.evar,params:"data\x3d"+d+"\x26_r\x3d"+1*new Date};if(!0!==h.a.noWeblog){c="http://"+h.a.log_host+h.a.log_path.event+
"?"+d.params;var k;k=k||h.a.max_delay;k=(new Date).getTime()+k;k>h.waitUntil&&(h.waitUntil=k);G(c)}!0===h.a.autoevent2app&&T(a,b,d.evar)}}function T(a,c,b){var d=e.FiredataAPP;d&&d.event(a,c,JSON.stringify(b||{}))}var F=e.navigator,x=e.screen,L=new Date,M=24+L.getHours()-L.getUTCHours(),E={width:x&&x.width,height:x&&x.height,ts:L.getTime(),timezone:0<M?"+"+M:""+M,sdk_version:"2.0",cl:x&&x.colorDepth,vp:function(){var a=d.body,c=a&&a.clientWidth&&a.clientHeight,b=[];x&&x.clientWidth&&x.clientHeight&&
("CSS1Compat"===d.compatMode||!c)?b=[x.clientWidth,x.clientHeight]:c&&(b=[a.clientWidth,a.clientHeight]);return 0>=b[0]||0>=b[1]?"":b.join("x")},dr:d.referrer,dt:d.title,fl:m(),st:e.sessionStorage?"1":"0",ck:F&&F.cookieEnabled?"1":"0",ln:F&&(F.language||F.browserLanguage||F.S||F.V||"").toLowerCase(),pvid:D()},B=[];B.push(function(){var a=Math.round((new Date).getTime()/1E3),b=y();if(!b.c||a-b.c>h.a.session_timeout)b.g++,b.c=b.u;Q(b);return{guid:b.f,guidts:b.m,guidvc:b.g,guidlvts:b.c,sessionid:b.f+
b.g}});B.push(function(){var a;a:{var b=w(c("ref"));if(b.length&&(b=JSON2.parse(b),C(b))){a=b;break a}a=["","",0,""]}var d=e.location.href,f,p,b=a[0];f=a[1];a=a[3];for(i in u.i)if(Object.prototype.hasOwnProperty.call(u.i,i)&&(p=J(d,u.i[i]),p.length)){b=p;break}for(i in u.h)if(Object.prototype.hasOwnProperty.call(u.h,i)&&(p=J(d,u.h[i]),p.length)){f=p;break}d=S(E.dr);d.length&&!U(d)&&(a=E.dr);return a.length||b.length?(d=Math.round((new Date).getTime()/1E3),a=[b,f,d,a.slice(0,1024)],r(c("ref"),JSON2.stringify(a),
15768E6,h.a.cookie_path,h.a.domain),{_ref:a[3],_refcn:b,_refcv:f,_refts:d}):{}});B.push(function(){var a=b("page");return v(a.name)?{pname:a.name}:v(u.o)?{pname:u.o}:{}});B.push(function(){var g;a:{g=w(c("u"));if(g.length&&(g=JSON2.parse(g),C(g)))break a;g={}}g=b("user",g);return a(g,{id:"uid"},"uvar")});B.push(function(){return a(b("content",u.l),{id:"cid",channel:"cch"},"cvar")});B.push(function(){var a=w(c("evt")),b=NaN;a&&(b=parseInt(a));isNaN(b)&&(b=0);r(c("evt"),b+1+"",339552E5,h.a.cookie_path,
h.a.domain);return{no:b}});B.push(function(){return a(b("event"),{},"evar")});var u={i:"fd_campaign _from _ref utm_campaign utm_source utm_medium qq-pf-to".split(" "),h:["fd_kwd","utm_term"],l:{},F:{},j:!0};Q();(function(){h.b(function(){A(e.document,"click",function(a){if(1==u.j){var b=a.target||a.srcElement,c=b.tagName.toUpperCase();if("INPUT"===c&&"button"===k(b,"type")||"BUTTON"===c)I(a);else if(p(b))!b._fd&&O&&A(b,"change",I);else if((a=t(b))&&!f(a)){c=a.evar||{};if(a.el&&"A"===a.el.tagName.toUpperCase()){var d=
k(a.el,"href");d&&(c.link=c.link||d);c.text=c.text||b.textContent||b.innerText}H(a.category,a.action,c)}}})})})();(function(){h.b(function(){O?N(["input","select","textarea"],function(){N(d.getElementsByTagName(this),function(){this._fd=!0;A(this,"change",I)})}):A(d,"change",I)})})();(function(){h.b(function(){var a=e.location.href,b=J(a,"__ec"),a=J(a,"__ea");b&&a&&H(b,a)})})();return{getGuid:function(){return y().f},setUserInfo:function(a){!v(a)||f(a)?r(c("u"),"",-86400,h.a.cookie_path,h.a.domain):
r(c("u"),JSON2.stringify(a),339552E5,h.a.cookie_path,h.a.domain)},setContentInfo:function(a){u.l=a||{}},P:function(a){E.dr=a},R:function(a){var b=e.location.href,c;R(a)||("/"===a.slice(0,1)?a=R(b)+"://"+S(b)+a:(c=b.indexOf("?"),0<=c&&(b=b.slice(0,c)),c=b.lastIndexOf("/"),c!==b.length-1&&(b=b.slice(0,c+1)),a=b+a));E.url=a},setDocumentTitle:function(a){E.dt=a},T:function(a,b,c){trackCallback(function(){logGoal(a,b,c)})},U:function(a,b,c,d){trackCallback(function(){logLink(a,b,c,d)})},pageView:function(a,
b){h.b(function(){var c=b;v(a)&&(u.o=a);c=c||{};!0===h.a.performanceTracking&&n&&n.timing&&n.timing.requestStart&&n.timing.responseEnd&&(c.perf=n.timing.responseEnd-n.timing.requestStart);H("/pv","pvStart",c)})},setParams:function(a){u.w=a||{}},event:function(a,b,c){h.b(function(){H(a,b,c)})},event2app:function(a,b,c){h.b(function(){T(a,b,c)})},autoEvent2app:function(a){h.a.autoevent2app=a}}};_fd=function(a,b){var c,d;for(c=0;c<b.length;c++){var e=b[c];for(d=0;d<a.length;d++)a[d]&&a[d][0]&&e===a[d][0]&&
(w(a[d]),delete a[d])}return a}(_fd,["setUserInfo","setContentInfo"]);for(iterator=0;iterator<_fd.length;iterator++)_fd[iterator]&&w(_fd[iterator]);_fd.push=w;var K={A:function(a){return a===Object(a)&&!K.isArray(a)},I:function(a){if(K.A(a)){for(var b in a)if(hasOwnProperty.call(a,b))return!1;return!0}return!1},L:function(a){return void 0===a},K:function(a){return"[object String]"==toString.call(a)},G:function(a){return"[object Date]"==toString.call(a)},J:function(a){return"[object Number]"==toString.call(a)},
H:function(a){return!(!a||1!==a.nodeType)},s:function(a){var b,c,d,e,f=0,h=0,k="",k=[];if(!a)return a;a=K.C(a);do b=a.charCodeAt(f++),c=a.charCodeAt(f++),d=a.charCodeAt(f++),e=b<<16|c<<8|d,b=e>>18&63,c=e>>12&63,d=e>>6&63,e&=63,k[h++]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".charAt(b)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".charAt(c)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".charAt(d)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".charAt(e);
while(f<a.length);k=k.join("");switch(a.length%3){case 1:k=k.slice(0,-2)+"\x3d\x3d";break;case 2:k=k.slice(0,-1)+"\x3d"}return k},C:function(a){a=(a+"").replace(/\r\n/g,"\n").replace(/\r/g,"\n");var b="",c,d,e=0,f;c=d=0;e=a.length;for(f=0;f<e;f++){var h=a.charCodeAt(f),k=null;128>h?d++:k=127<h&&2048>h?String.fromCharCode(h>>6|192,h&63|128):String.fromCharCode(h>>12|224,h>>6&63|128,h&63|128);null!==k&&(d>c&&(b+=a.substring(c,d)),b+=k,c=d=f+1)}d>c&&(b+=a.substring(c,a.length));return b}};e[y]=e[y]||
h})(window,"FireData");