
"object"!==typeof JSON2&&(JSON2=window.JSON||{});
(function(){function b(b){return 10>b?"0"+b:b}function z(b){G.lastIndex=0;return G.test(b)?'"'+b.replace(G,function(b){var f=l[b];return"string"===typeof f?f:"\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+b+'"'}function v(t,A){var f,m,p,l,w=k,n,c=A[t];c&&"object"===typeof c&&(f=c,p=Object.prototype.toString.apply(f),c="[object Date]"===p?isFinite(f.valueOf())?f.getUTCFullYear()+"-"+b(f.getUTCMonth()+1)+"-"+b(f.getUTCDate())+"T"+b(f.getUTCHours())+":"+b(f.getUTCMinutes())+":"+b(f.getUTCSeconds())+
"Z":null:"[object String]"===p||"[object Number]"===p||"[object Boolean]"===p?f.valueOf():"[object Array]"!==p&&"function"===typeof f.toJSON?f.toJSON(t):f);"function"===typeof q&&(c=q.call(A,t,c));switch(typeof c){case "string":return z(c);case "number":return isFinite(c)?String(c):"null";case "boolean":case "null":return String(c);case "object":if(!c)return"null";k+=B;n=[];if("[object Array]"===Object.prototype.toString.apply(c)){l=c.length;for(f=0;f<l;f+=1)n[f]=v(f,c)||"null";p=0===n.length?"[]":
k?"[\n"+k+n.join(",\n"+k)+"\n"+w+"]":"["+n.join(",")+"]";k=w;return p}if(q&&"object"===typeof q)for(l=q.length,f=0;f<l;f+=1)"string"===typeof q[f]&&(m=q[f],(p=v(m,c))&&n.push(z(m)+(k?": ":":")+p));else for(m in c)Object.prototype.hasOwnProperty.call(c,m)&&(p=v(m,c))&&n.push(z(m)+(k?": ":":")+p);p=0===n.length?"{}":k?"{\n"+k+n.join(",\n"+k)+"\n"+w+"}":"{"+n.join(",")+"}";k=w;return p}}var x=RegExp("[\x00­؀-؄܏឴឵‌-‏\u2028- ⁠-⁯﻿￰-￿]","g"),G=RegExp('[\\\\\\"\x00--­؀-؄܏឴឵‌-‏\u2028- ⁠-⁯﻿￰-￿]',"g"),k,
B,l={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},q;"function"!==typeof JSON2.stringify&&(JSON2.stringify=function(b,l,f){var m;B=k="";if("number"===typeof f)for(m=0;m<f;m+=1)B+=" ";else"string"===typeof f&&(B=f);if((q=l)&&"function"!==typeof l&&("object"!==typeof l||"number"!==typeof l.length))throw Error("JSON2.stringify");return v("",{"":b})});"function"!==typeof JSON2.parse&&(JSON2.parse=function(b,l){function f(b,m){var k,n,c=b[m];if(c&&"object"===typeof c)for(k in c)Object.prototype.hasOwnProperty.call(c,
k)&&(n=f(c,k),void 0!==n?c[k]=n:delete c[k]);return l.call(b,m,c)}var m;b=String(b);x.lastIndex=0;x.test(b)&&(b=b.replace(x,function(b){return"\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(b.replace(RegExp('\\\\(?:["\\\\/bfnrt]|u[0-9a-fA-F]{4})',"g"),"@").replace(RegExp('"[^"\\\\\n\r]*"|true|false|null|-?\\d+(?:\\.\\d*)?(?:[eE][+\\-]?\\d+)?',"g"),"]").replace(RegExp("(?:^|:|,)(?:\\s*\\[)+","g"),"")))return m=eval("("+b+")"),"function"===typeof l?f({"":m},""):m;throw new SyntaxError("JSON2.parse");
})})();"object"!==typeof _fd&&(_fd=[]);
(function(b,z,v){function x(){var a,g,e;for(a=0;a<arguments.length;a+=1)e=arguments[a],g=e.shift(),"string"===typeof g||g instanceof String?asyncTracker[g].apply(asyncTracker,e):g.apply(asyncTracker,e)}function G(a){var g=new Image,e="ab_log_"+Math.round(2147483647*Math.random()).toString(36);b[e]=g;g.onload=g.onerror=g.onabort=function(){g.onload=g.onerror=g.onabort=null;g=b[e]=null};g.src=a}function k(){var a,g,e;if((e=(e=b.navigator)?e.plugins:null)&&e.length)for(var c=0;c<e.length&&!g;c++){var f=
e[c];-1<f.name.indexOf("Shockwave Flash")&&(g=f.description)}if(!g)try{a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"),g=a.GetVariable("$version")}catch(h){}if(!g)try{a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),g="WIN 6,0,21,0",a.w="always",g=a.GetVariable("$version")}catch(h){}if(!g)try{a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),g=a.GetVariable("$version")}catch(h){}g&&(a=g.match(/[\d]+/g))&&2<=a.length&&(g=a[0]+"."+a[1]);return g||void 0}function B(){for(var a=b.navigator,
a=a.appName+a.version+a.platform+a.userAgent+(c.cookie?c.cookie:"")+(c.referrer?c.referrer:""),g=a.length,e=b.history.length;0<e;)a+=e--^g++;var g=1,e=0,C;if(a)for(g=0,C=a.length-1;0<=C;C--)e=a.charCodeAt(C),g=(g<<6&268435455)+e+(e<<14),e=g&266338304,0!=e&&(g^=e>>21);return[Math.round(2147483647*Math.random())^g&2147483647,Math.round((new Date).getTime())].join("")}function l(a,g){if(a&&a.getAttribute)return a.getAttribute(g);if(!a||!a.attributes||"undefined"===typeof a.attributes[g])return v;if(a.attributes[g].value)return a.attributes[g].value;
if(a.attributes[g].nodeValue)return a.attributes[g].nodeValue;var e,c=a.attributes;if(!c)return v;for(e=0;e<c.length;e++)if(c[e].nodeName===g)return c[e].nodeValue;return v}function q(a){return a&&"object"===typeof a&&a.length&&"number"===typeof a.length}function t(a){return null!==a&&"undefined"!==typeof a}function A(a){return"object"===typeof a}function f(a){for(var c in a)return!1;return!0}function m(){for(var a,c,e,b,f,h=arguments[0]||{},l=arguments.length,k=1;k<l;k++)if(null!=(f=arguments[k]))for(b in f)a=
h[b],e=f[b],h!==e&&(e&&(A(e)||(c=q(e)))?(c?(c=!1,a=a&&q(a)?a:[]):a=a&&A(a)?a:{},h[b]=m(a,e)):e!==v&&(h[b]=e));return h}function p(a){return a&&"function"===typeof a?p(a()):A(a)||q(a)?JSON2.stringify(a):t(a)?String(a):""}function N(a,c){var b,f=0,h=a.length;if(q(a))for(;f<h&&(b=c.call(a[f],f,a[f]),!1!==b);f++);else for(f in a)if(b=c.call(a[f],f,a[f]),!1===b)break}function w(a,c,b,f){a.attachEvent?a.attachEvent("on"+c,function(c){b.call(a,c)}):a.addEventListener&&a.addEventListener(c,b,!!f)}var n=b.performance||
b.B||b.C||b.L,c=b.document,T=c.all&&b.XMLHttpRequest&&!c.querySelector,U=c.all&&c.querySelector&&!c.addEventListener,V=c.all&&c.addEventListener&&!b.atob,O=c.all&&c.compatMode&&!b.XMLHttpRequest||T||U||V,h={a:{"autoEvent":true,"cmpKws":["fd_kwd","utm_term"],"cmpParams":["fd_campaign","_from","_ref","utm_campaign","utm_source","utm_medium","qq-pf-to"],"domain":"facebank.cn","host_alias":["facebank.net.cn"],"log_host":"collect.facebank.cn","log_path":{"event":"/log/9WAI779FPB/event"},"max_delay":300,"performanceTracking":true,"session_timeout":1800,"app_key":"9WAI779FPB","site_id":"9WAI779FPB"}};h.a.host_alias.push(c.domain);h.waitUntil=0;h.c=function(){function a(){if(!h){h=
!0;for(var a=0;a<m.length;a++)m[a]()}}function f(){c.addEventListener?(c.removeEventListener("DOMContentLoaded",e,!1),b.removeEventListener("load",e,!1)):(c.detachEvent("onreadystatechange",e),b.detachEvent("onload",e))}function e(){if(c.addEventListener||"load"===event.type||"complete"===c.readyState)f(),a()}var h=!1,m=[];if("complete"===c.readyState)setTimeout(a);else if(c.addEventListener)c.addEventListener("DOMContentLoaded",e,!1),b.addEventListener("load",e,!1);else{c.attachEvent("onreadystatechange",
e);b.attachEvent("onload",e);var l=!1;try{l=null==b.frameElement&&c.documentElement}catch(k){}l&&l.doScroll&&function D(){if(!h){try{l.doScroll("left")}catch(c){return setTimeout(D,50)}f();a()}}()}return function(a){h?a():m.push(a)}}();w(b,"beforeunload",function(){var a;if(h.waitUntil){do a=new Date;while(a.getTime()<h.waitUntil)}},!1);asyncTracker=new function(){function a(d,a,c){var b={},e={},g;for(g in d)a.hasOwnProperty(g)?b[a[g]]=d[g]:e[g]=d[g];f(e)||(b[c]=e);return b}function g(d,a){for(var b=
a||{},e=c.getElementsByTagName("Meta"),f=0;f<e.length;f+=1){var g=e[f],h=l(g,"name");h&&0==h.indexOf(d+"-")&&(b[h.substring(d.length+1)]=l(g,"content"))}return b}function e(d){return"_fd_"+d+"."+h.a.site_id}function C(d){d=d.tagName.toUpperCase();return"INPUT"===d||"SELECT"===d||"TEXTAREA"===d}function q(d){if(!1!==r.j&&(d=d.target||d.srcElement)){var a=x(d),c=a.category;!a.category&&t(d.form)&&(c="/form/"+(d.form.id||d.form.name));if(t(c)&&C(d)){var b=d.value||"",e=a.action||d.name||d.id||"",a=m({len:b.length},
a.evar);"password"!==l(d,"type")&&"@off"!==a.v&&(a.v=b);H(c,e,a)}}}function x(d){for(var a=0,b={};d&&d!==c&&d.parentNode;){if(!b.action&&l(d,"data-event")||C(d)){b.el=d;b.action=l(d,"data-event")||v;var e;if(d&&d.attributes){e=void 0;var f=d.attributes,g={};for(e=0;e<f.length;e++){var h=f[e],k=h.nodeName||h.name;0==k.indexOf("data-event-")&&(g[k.substring(11)]=h.nodeValue||h.value)}e=g}else e={};f=e;g={};for(name in f)"category"!==name&&(g[name]=f[name]);b.evar=m(b.evar,g);if(e.category){b.category=
e.category;break}}if(!b.category&&l(d,"data-event-category")){b.category=l(d,"data-event-category");break}d=d.parentNode;if(100<a)break;a++}return b}function z(d){var a,b,c;for(a=0;a<h.a.host_alias.length;a++){b=h.a.host_alias[a].toLowerCase();if(d===b)return!0;if("."===b.slice(0,1)){if(d===b.slice(1))return!0;c=d.length-b.length;if(0<c&&d.slice(c)===b)return!0}}return!1}function D(d,a,e,f,g){var h;e&&(h=new Date,h.setTime(h.getTime()+e));"auto"==g&&(g=b.location.hostname);c.cookie=d+"\x3d"+b.encodeURIComponent(a)+
(e?";expires\x3d"+h.toGMTString():"")+";path\x3d"+(f||"/")+(g?";domain\x3d"+g:"")+""}function I(d){return(d=(new RegExp("(^|;)[ ]*"+d+"\x3d([^;]*)")).exec(c.cookie))?b.decodeURIComponent(d[2]):0}function K(){var d;d=Math.round((new Date).getTime()/1E3);var a=I(e("id"));a?(d=a.split("."),d.unshift("0")):d=["1",B(),d,0,d,"",""];return{D:d[0],f:d[1],m:d[2],g:d[3],s:d[4],b:d[5],u:d[6]}}function P(d){var a=Math.round((new Date).getTime()/1E3);t(d)||(d=K());D(e("id"),d.f+"."+d.m+"."+d.g+"."+a+"."+d.b+"."+
d.u,339552E5,h.a.cookie_path,h.a.domain)}function Q(d){return(d=/^([a-z]+):/.exec(d))?d[1]:null}function R(d){var a=/^(?:(?:https?|ftp):)\/*(?:[^@]+@)?([^:/#]+)/.exec(d);return a?a[1]:d}function J(d,a){var c=(new RegExp("[\\?\x26#]"+a+"\x3d([^\x26#]*)")).exec(d);return c?b.decodeURIComponent(c[1]):""}function H(d,a,b){if(0!==String(d).length&&0!==String(a).length){"/"!=d.charAt(0)&&(d="/"+d);b=m({},b);var c="http://"+h.a.log_host+h.a.log_path.event+"?",e={_ecat:d,_eact:a,evar:b},g,f,l=[],k={};for(f in E)g=
p(E[f]),!g.length||e&&e.hasOwnProperty(f)||l.push(f+"\x3d"+encodeURIComponent(g));for(g=0;g<y.length;g+=1)m(k,y[g]());k.hasOwnProperty("evar")&&(e.evar=m(k.evar,e.evar||{}));e&&m(k,e);for(f in k)g=p(k[f]),g.length&&l.push(f+"\x3d"+encodeURIComponent(g));l.push("_r\x3d"+String(Math.random()).slice(2,8));var c=c+l.join("\x26"),n;n=n||h.a.max_delay;n=(new Date).getTime()+n;n>h.waitUntil&&(h.waitUntil=n);G(c);!0===h.a.autoevent2app&&S(d,a,b)}}function S(d,a,c){var e=b.FiredataAPP;e&&e.event(d,a,JSON.stringify(c||
{}))}var F=b.navigator,u=b.screen,L=new Date,M=24+L.getHours()-L.getUTCHours(),E={width:u&&u.width,height:u&&u.height,ts:L.getTime(),timezone:0<M?"+"+M:""+M,sdk_version:"2.0",cl:u&&u.colorDepth,vp:function(){var d=c.body,a=d&&d.clientWidth&&d.clientHeight,b=[];u&&u.clientWidth&&u.clientHeight&&("CSS1Compat"===c.compatMode||!a)?b=[u.clientWidth,u.clientHeight]:a&&(b=[d.clientWidth,d.clientHeight]);return 0>=b[0]||0>=b[1]?"":b.join("x")},dr:c.referrer,dt:c.title,fl:k(),st:b.sessionStorage?"1":"0",ck:F&&
F.cookieEnabled?"1":"0",ln:F&&(F.language||F.browserLanguage||F.H||F.K||"").toLowerCase(),pvid:B()},y=[];y.push(function(){var d=Math.round((new Date).getTime()/1E3),a=K();if(!a.b||d-a.b>h.a.session_timeout)a.g++,a.b=a.s;P(a);return{guid:a.f,guidts:a.m,guidvc:a.g,guidlvts:a.b,sessionid:a.f+a.g}});y.push(function(){var d;a:{var a=I(e("ref"));if(a.length&&(a=JSON2.parse(a),A(a))){d=a;break a}d=["","",0,""]}var c=b.location.href,g,f,a=d[0];g=d[1];d=d[3];for(i in r.i)if(Object.prototype.hasOwnProperty.call(r.i,
i)&&(f=J(c,r.i[i]),f.length)){a=f;break}for(i in r.h)if(Object.prototype.hasOwnProperty.call(r.h,i)&&(f=J(c,r.h[i]),f.length)){g=f;break}c=R(E.dr);c.length&&!z(c)&&(d=E.dr);return d.length||a.length?(c=Math.round((new Date).getTime()/1E3),d=[a,g,c,d.slice(0,1024)],D(e("ref"),JSON2.stringify(d),15768E6,h.a.cookie_path,h.a.domain),{_ref:d[3],_refcn:a,_refcv:g,_refts:c}):{}});y.push(function(){var a=g("page");return t(a.name)?{pname:a.name}:t(r.o)?{pname:r.o}:{}});y.push(function(){var d;a:{d=I(e("u"));
if(d.length&&(d=JSON2.parse(d),A(d)))break a;d={}}d=g("user",d);return a(d,{id:"uid"},"uvar")});y.push(function(){return a(g("content",r.l),{id:"cid",channel:"cch"},"cvar")});y.push(function(){var a=I(e("evt")),b=NaN;a&&(b=parseInt(a));isNaN(b)&&(b=0);D(e("evt"),b+1+"",339552E5,h.a.cookie_path,h.a.domain);return{no:b}});y.push(function(){return a(g("event"),{},"evar")});var r={i:"fd_campaign _from _ref utm_campaign utm_source utm_medium qq-pf-to".split(" "),h:["fd_kwd","utm_term"],l:{},A:{},j:!0};
P();(function(){h.c(function(){w(b.document,"click",function(a){if(1==r.j){var b=a.target||a.srcElement,c=b.tagName.toUpperCase();if("INPUT"===c&&"button"===l(b,"type")||"BUTTON"===c)q(a);else if(C(b))!b._fd&&O&&w(b,"change",q);else if((a=x(b))&&!f(a)){c=a.evar||{};if(a.el&&"A"===a.el.tagName.toUpperCase()){var e=l(a.el,"href");e&&(c.link=c.link||e);c.text=c.text||b.textContent||b.innerText}H(a.category,a.action,c)}}})})})();(function(){h.c(function(){O?N(["input","select","textarea"],function(){N(c.getElementsByTagName(this),
function(){this._fd=!0;w(this,"change",q)})}):w(c,"change",q)})})();(function(){var a=b.location.href,c=J(a,"__ec"),a=J(a,"__ea");c&&a&&H(c,a)})();return{getGuid:function(){return K().f},setUserInfo:function(a){!t(a)||f(a)?D(e("u"),"",-86400,h.a.cookie_path,h.a.domain):D(e("u"),JSON2.stringify(a),339552E5,h.a.cookie_path,h.a.domain)},setContentInfo:function(a){r.l=a||{}},F:function(a){E.dr=a},G:function(a){var c=b.location.href,e;Q(a)||("/"===a.slice(0,1)?a=Q(c)+"://"+R(c)+a:(e=c.indexOf("?"),0<=
e&&(c=c.slice(0,e)),e=c.lastIndexOf("/"),e!==c.length-1&&(c=c.slice(0,e+1)),a=c+a));E.url=a},setDocumentTitle:function(a){E.dt=a},I:function(a,c,b){trackCallback(function(){logGoal(a,c,b)})},J:function(a,c,b,e){trackCallback(function(){logLink(a,c,b,e)})},pageView:function(a,c){h.c(function(){var b=c;t(a)&&(r.o=a);b=b||{};!0===h.a.performanceTracking&&n&&n.timing&&n.timing.requestStart&&n.timing.responseEnd&&(b.perf=n.timing.responseEnd-n.timing.requestStart);H("/pv","pvStart",b)})},event:function(a,
c,b){h.c(function(){H(a,c,b)})},event2app:function(a,c,b){h.c(function(){S(a,c,b)})},autoEvent2app:function(a){h.a.autoevent2app=a}}};_fd=function(a,c){var b,f;for(b=0;b<c.length;b++){var h=c[b];for(f=0;f<a.length;f++)a[f]&&a[f][0]&&h===a[f][0]&&(x(a[f]),delete a[f])}return a}(_fd,["setUserInfo","setContentInfo"]);for(iterator=0;iterator<_fd.length;iterator++)_fd[iterator]&&x(_fd[iterator]);_fd.push=x;b[z]=b[z]||h})(window,"FireData");